name: Bug Report
description: Use this template to report a bug.
title: "[BUG] - "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide the following details:

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the issue.
      placeholder: Step 1, Step 2, ...

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What happened instead of the expected behavior?
      placeholder: Describe the actual behavior...
